-- Grade Change Intelligence: minimal operational and historical analysis schema.
--
-- This script uses SQL types understood by SQLite and PostgreSQL. Enable foreign
-- keys explicitly for each SQLite connection: PRAGMA foreign_keys = ON;
-- In SQLite, INTEGER PRIMARY KEY auto-generates a rowid when omitted. For a
-- PostgreSQL production deployment, use the equivalent `GENERATED BY DEFAULT
-- AS IDENTITY` definition for process_data_log.id if database-generated IDs are
-- required rather than IDs supplied by an ingestion service.

-- Real-time paper-machine measurements retained for feature validation and trends.
CREATE TABLE process_data_log (
    id INTEGER PRIMARY KEY,
    timestamp TIMESTAMP NOT NULL,
    stock_flow NUMERIC NOT NULL,
    steam_pressure NUMERIC NOT NULL,
    machine_speed NUMERIC NOT NULL,
    moisture NUMERIC NOT NULL CHECK (moisture >= 0 AND moisture <= 100),
    basis_weight NUMERIC NOT NULL,
    grade TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- System-generated recommendations. recommendation_id directly replaces the
-- API's current in-memory recommendation_store key.
CREATE TABLE recommendations (
    recommendation_id TEXT PRIMARY KEY,
    risk_score NUMERIC NOT NULL CHECK (risk_score >= 0 AND risk_score <= 100),
    predicted_deviation NUMERIC NOT NULL,
    action TEXT NOT NULL,
    confidence NUMERIC NOT NULL CHECK (confidence >= 0 AND confidence <= 100),
    similar_cases INTEGER NOT NULL,
    success_rate NUMERIC NOT NULL CHECK (success_rate >= 0 AND success_rate <= 100),
    avg_stabilization_minutes INTEGER NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    grade TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Operator responses, retained for outcome analysis and evidence-engine updates.
CREATE TABLE feedback (
    feedback_id TEXT PRIMARY KEY,
    recommendation_id TEXT NOT NULL,
    operator_response TEXT NOT NULL CHECK (operator_response IN ('accept', 'reject')),
    timestamp TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (recommendation_id)
        REFERENCES recommendations(recommendation_id)
);

-- Query-path indexes: trends, historical risk bands, and feedback lookups.
CREATE INDEX idx_process_data_log_timestamp ON process_data_log (timestamp);
CREATE INDEX idx_recommendations_timestamp ON recommendations (timestamp);
CREATE INDEX idx_recommendations_risk_score ON recommendations (risk_score);
CREATE INDEX idx_feedback_recommendation_id ON feedback (recommendation_id);
CREATE INDEX idx_feedback_created_at ON feedback (created_at);

-- Demo process readings for the three deterministic API scenarios.
INSERT INTO process_data_log
    (id, timestamp, stock_flow, steam_pressure, machine_speed, moisture, basis_weight, grade, created_at)
VALUES
    (1, '2026-07-25T14:00:00Z', 150.0, 8.5, 900.0, 5.2, 20.2, 'Copy Paper 20lb', '2026-07-25T14:00:00Z'),
    (2, '2026-07-25T14:05:00Z', 140.0, 8.9, 880.0, 5.6, 18.8, 'Copy Paper 18lb', '2026-07-25T14:05:00Z'),
    (3, '2026-07-25T14:10:00Z', 165.0, 8.2, 950.0, 4.8, 19.5, 'Newsprint 24lb', '2026-07-25T14:10:00Z');

-- Demo recommendations and accepted operator responses.
INSERT INTO recommendations
    (recommendation_id, risk_score, predicted_deviation, action, confidence, similar_cases, success_rate, avg_stabilization_minutes, timestamp, grade, created_at)
VALUES
    ('a1111111-1111-4111-8111-111111111111', 68, 3.1, 'Reduce Stock Flow: 2%', 91, 18, 89, 8, '2026-07-25T14:00:00Z', 'Copy Paper 20lb', '2026-07-25T14:00:00Z'),
    ('b2222222-2222-4222-8222-222222222222', 84, -4.8, 'Increase Steam: 3% + Reduce Speed: 1%', 76, 5, 60, 15, '2026-07-25T14:05:00Z', 'Copy Paper 18lb', '2026-07-25T14:05:00Z'),
    ('c3333333-3333-4333-8333-333333333333', 22, 0.3, 'Maintain current parameters', 97, 42, 98, 2, '2026-07-25T14:10:00Z', 'Newsprint 24lb', '2026-07-25T14:10:00Z');

INSERT INTO feedback
    (feedback_id, recommendation_id, operator_response, timestamp, created_at)
VALUES
    ('fa111111-1111-4111-8111-111111111111', 'a1111111-1111-4111-8111-111111111111', 'accept', '2026-07-25T14:01:00Z', '2026-07-25T14:01:00Z'),
    ('fb222222-2222-4222-8222-222222222222', 'b2222222-2222-4222-8222-222222222222', 'accept', '2026-07-25T14:06:00Z', '2026-07-25T14:06:00Z'),
    ('fc333333-3333-4333-8333-333333333333', 'c3333333-3333-4333-8333-333333333333', 'accept', '2026-07-25T14:11:00Z', '2026-07-25T14:11:00Z');
