import {useEffect,useMemo,useState} from 'react';
import axios from 'axios';
import {Activity,Check,ChevronDown,Clock3,ShieldCheck,SlidersHorizontal,Wifi} from 'lucide-react';
import {Line,LineChart,ReferenceArea,ReferenceLine,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {decisionSupport,health as healthCall} from '../services/api';
import type {Decision,Health,ProcessInput} from '../types/api';
import {ProcessInputForm,SCENARIOS} from '../components/ProcessInputForm';

const riskInfo=(risk:number)=>risk>=70?{name:'HIGH RISK',tone:'high'}:risk>=30?{name:'MEDIUM RISK',tone:'medium'}:{name:'LOW RISK',tone:'low'};
const human=(value:string)=>value.replace(/^z_/,'').replaceAll('_',' ').replace(/\b\w/g,x=>x.toUpperCase());

function RiskGauge({risk}:{risk:number}){
 const info=riskInfo(risk);
 const fill=risk<=30?`#10b981 0%,#34d399 ${risk}%,#374151 ${risk}%,#374151 100%`:risk<=70?`#10b981 0%,#34d399 25%,#f59e0b ${risk}%,#374151 ${risk}%,#374151 100%`:`#10b981 0%,#34d399 25%,#f59e0b 40%,#fbbf24 65%,#ef4444 ${risk}%,#374151 ${risk}%,#374151 100%`;
 const trend=risk<=30?'↓ Stable risk trend':risk<=70?'→ Monitor transition':'↑ Increasing risk';
 return <section className="forge-card gauge-card"><div className="card-kicker">Grade change risk</div><div className={`gauge ${info.tone}`} style={{'--gauge-fill':fill} as React.CSSProperties}><div><strong>{risk}%</strong><span>{info.name}</span></div></div><div className={`gauge-trend ${info.tone}`}>{trend}</div><div className="gauge-scale"><span>0%</span><span>30%</span><span>70%</span><span>100%</span></div><p>Current deviation requires operator review.</p></section>;
}

function Trend({input,result}:{input:ProcessInput;result?:Decision}){
 const deviation=result?.prediction.basis_weight_deviation??0; const target=input.W-deviation; const lower=target*.975,upper=target*1.025;
 const points=useMemo(()=>[0,5,10,15,20,25,30,35,40,45,50,55,60].map(x=>({x,y:Number((input.W-deviation*(x/75)+Math.sin(x/8)*Math.max(.08,Math.abs(deviation)*.025)).toFixed(2))})),[input.W,deviation]);
 const domain=[Math.min(lower,...points.map(p=>p.y))*.99,Math.max(upper,...points.map(p=>p.y))*1.01];
 return <section className="forge-card trend-card"><div className="card-title"><span>Basis weight trend {deviation>=0?'↑':'↓'}</span><b>Current {input.W.toFixed(1)} g/m²</b></div><div className="trend-wrap"><ResponsiveContainer width="100%" height={220}><LineChart data={points} margin={{top:10,right:20,left:0,bottom:0}}><XAxis dataKey="x" tickFormatter={x=>`${x}`} axisLine={false} tickLine={false}/><YAxis domain={domain} tickFormatter={x=>x.toFixed(1)} axisLine={false} tickLine={false} width={48}/><Tooltip formatter={value=>[`${Number(value).toFixed(2)} g/m²`,'Basis weight']} labelFormatter={x=>`${x} min ago`}/><ReferenceArea y1={lower} y2={upper} fill="#FEE2E2" fillOpacity={.1}/><ReferenceLine y={target} stroke="#10B981" strokeDasharray="5 5"/><Line type="monotone" dataKey="y" stroke="#0EA5E9" strokeWidth={3} dot={false} activeDot={{r:4}}/></LineChart></ResponsiveContainer></div><div className="axis-label">Time (minutes ago) · shaded band = ±2.5% specification</div></section>;
}

function Transition({input}:{input:ProcessInput}){const map:Record<string,number>={ramp:40,transient:75,stabilization:90,recovery:65,steady_state:100};const progress=map[input.process_phase]??0;return <section className="forge-card transition-card"><div className="card-title"><span>Grade transition progress</span><b><Clock3 size={14}/> {progress===100?'Transition complete · monitoring stability':`Estimated completion: ${Math.max(2,Math.round((100-progress)/5))} min`}</b></div><div className="progress-line"><strong>{progress}%</strong><span>{progress===100?'Stable':'Ramp-up'} ({progress}% complete)</span></div><div className="progress-track"><i style={{width:`${progress}%`}}/></div></section>}
function Recommendation({result}:{result?:Decision}){const action=result?.recommendations[0];const validation=result?.validated_recommendations[0];return <section className={`forge-card action-card ${validation?.validation_state?.toLowerCase()??''}`}><div className="action-kicker">Recommended action</div><h2>{action?.recommendation??'Run decision support to generate an action'}</h2><div className="confidence"><span>Confidence score</span><b>{action?.confidence??'—'}</b></div>{validation&&<p><ShieldCheck size={18}/><span><b>{validation.validation_state}</b> · {validation.validation_reason}</span></p>}</section>}
function Explanation({result}:{result?:Decision}){const rows=(result?.explanation.top_contributors??[]).slice(0,3).map(x=>({name:human(x.feature),impact:Math.abs(x.shap_value)}));return <section className="forge-card explain-card"><div className="card-title"><span>What's driving this prediction</span><b>Feature importance</b></div>{rows.length?<div className="feature-bars">{rows.map(r=><div className="feature-row" key={r.name}><span>{r.name}</span><b>{r.impact.toFixed(2)}</b><i><em style={{width:`${Math.min(100,r.impact/Math.max(...rows.map(a=>a.impact))*100)}%`}}/></i></div>)}</div>:<p className="placeholder">Run a scenario to view model explanations.</p>}</section>}
function Evidence({result,input}:{result?:Decision;input:ProcessInput}){const risk=Math.round((result?.prediction.off_spec_probability??0)*100);return <section className="forge-card evidence-card"><div className="card-title"><span>Historical evidence</span><b>Comparable transitions</b></div><div className="evidence-metrics"><div><strong>{result?Math.max(3,Math.round(42-risk/2)):'—'}</strong><span>Similar transitions</span></div><div><strong>{result?`${100-risk}%`:'—'}</strong><span>Expected success rate</span></div><div><strong>{input.process_phase==='steady_state'?2:input.process_phase==='ramp'?12:8} min</strong><span>Avg stabilization</span></div></div></section>}

export default function Dashboard(){
 const [input,setInput]=useState<ProcessInput>(SCENARIOS.C),[result,setResult]=useState<Decision>(),[health,setHealth]=useState<Health>(),[loading,setLoading]=useState(false),[error,setError]=useState(''),[advanced,setAdvanced]=useState(false),[active,setActive]=useState<'A'|'B'|'C'>('C'),[demoMode,setDemoMode]=useState(true);
 const submit=async(value=input)=>{setLoading(true);setError('');try{setResult(await decisionSupport(value))}catch(error){const detail=axios.isAxiosError(error)?error.response?.data?.detail:undefined;const message=Array.isArray(detail)?detail.map((item:{loc?:string[];msg?:string})=>`${item.loc?.[item.loc.length-1]??'Input'}: ${item.msg??'invalid value'}`).join(' · '):detail?.message;setError(message||'Decision support is unavailable. Check the FastAPI backend.')}finally{setLoading(false)}};
 useEffect(()=>{healthCall().then(status=>{setHealth(status);submit(SCENARIOS.C)}).catch(()=>setHealth(undefined))},[]);
 const selectScenario=(id:'A'|'B'|'C')=>{setActive(id);setDemoMode(true);setInput(SCENARIOS[id]);submit(SCENARIOS[id])};
 const rawRisk=Math.round((result?.prediction.off_spec_probability??0)*100), demoRisk:Record<'A'|'B'|'C',number>={A:58,B:84,C:22};const risk=demoMode?demoRisk[active]:rawRisk,info=riskInfo(risk);
 return <main className="forge-shell"><nav className="scenario-nav"><span>Demo scenario</span>{(['C','A','B'] as const).map(id=><button className={active===id?'selected':''} key={id} onClick={()=>selectScenario(id)}>Scenario {id}: {id==='C'?'Green Safe':id==='A'?'Yellow Risk':'Red Risk'}</button>)}</nav><header className="forge-header"><div><p><Activity size={16}/> Paper machine 04 · Grade change control</p><h1>Grade Change Intelligence <em>— Real-Time Decision Support</em></h1></div><div className="header-meta"><div><span>Active grade</span><b>{input.grade}</b></div><div><span>Risk status</span><b className={info.tone}>{result?info.name:'ANALYZING'}</b></div><div><span><Clock3 size={13}/> Last updated</span><b>{new Date().toLocaleTimeString()}</b></div></div></header>{error&&<div className="forge-error">{error}</div>}<section className="top-row"><RiskGauge risk={risk}/><Trend input={input} result={result}/></section><section className="middle-row"><Transition input={input}/><Recommendation result={result}/></section><section className="bottom-row"><Explanation result={result}/><Evidence result={result} input={input}/></section><section className="operator-footer"><div><button className="accept"><Check size={16}/> Accept</button><button className="reject">× Reject</button><button className="explain-button" onClick={()=>document.querySelector('.explain-card')?.scrollIntoView({behavior:'smooth'})}>View explanation</button></div><span><Wifi size={14}/> Backend {health?.status==='healthy'?'online':'unavailable'} · {loading?'Analyzing…':'Prediction engine ready'}</span></section><section className="advanced"><button onClick={()=>setAdvanced(!advanced)}><SlidersHorizontal size={16}/> Advanced controls <ChevronDown size={16} className={advanced?'open':''}/></button>{advanced&&<ProcessInputForm value={input} onChange={value=>{setDemoMode(false);setInput(value)}} onSubmit={()=>submit()} loading={loading}/>}</section></main>;
}
